(in-package :eliza-test)

(defparameter *eliza-rules-pt*
  '((((?* ?x) Ola (?* ?y))
     (Ola eu sou a Eliza. Qual o seu nome?))
    (((?* ?x) Eu me chamo (?* ?y))
     (Prazer em conhece-lo ?y Por favor fale sobre o seu problema.))
    (((?* ?x) Eu quero (?* ?y))
     (O que significaria se voce conseguisse ?y ?)
     (Por que voce quer ?y ?) 
     (Voce acredita que conseguira ?y ?))
    (((?* ?x) Eu estou (?* ?y))
     (Por que voce esta ?y ?)
     (Voce quer estar ?y ?))
    (((?* ?x) Nao (?* ?y))
     (Por que nao?)
     (Voce esta sendo um pouco negativo))
    (((?* ?x) Desculpe (?* ?y))
     (Por favor nao se Desculpe))
    (((?* ?x) Triste (?* ?y))
     (Voce nao deveria se sentir triste por algo assim)
     (E ruim saber que voce nao esta feliz))
    (((?* ?x) minha mae (?* ?y))
     (Conte-me mais sobre sua familia)
     (Quem mais e da sua familia?))
    (((?* ?x) meu pai (?* ?y))
     (Ele influencia na sua vida?)
     (O que voce pensa sobre seu pai?))
    (((?* ?x) sonho (?* ?y))
     (Com o que mais voce sonha?)
     (Que pessoas apareceram em seus sonhos?))
    (((?* ?x) eu quero (?* ?y))
     (Por que voce quer ?y ?)
     (O que voce fara quando tiver ?y ?))
    (((?* ?x) sonhei com (?* ?y))
     (Voce gosta de ?y)
     (Por que voce acha que sonhou com ?y ?))
    (((?* ?x) gosto (?* ?y))
     (Por que voce gosta tanto de ?y ?)
     (Sera que voce gosta tanto de ?y quanto voce pensa?))
    (((?* ?x) Tchau (?* ?y))
     (Nao se va!)
     (Logo agora que estamos no auge da nossa conversa?))
    (((?* ?x) sim (?* ?y))
     (Eu compreendo)
     (Fico feliz com essa sua positividade))
    (((?* ?x) eu sinto (?* ?y))
     (Com que frequencia voce sente ?y ?)
    (((?* ?x) porque (?* ?y))
     (Esse e o real motivo?)
     (Tem certeza que e isso?))
     (((?* ?x) nao gosto (?* ?y))
     (Porque sera que voce nao gosta?)
      (O que faz voce nao gostar?))
     (((?* ?x) Eu sou (?* ?y))
     (Serio que voce e ?y ?)
      (Conte-me mais sobre ser ?y ))
    (((?* ?x) Por que (?* ?y))
     (Esse e o verdadeiro motivo?)
     (Quais outros motivos poderiam existir?)
     (Esse motivo pode explicar alguma outra coisa?))))


(defun switch-viewpoint (words)
  (sublis '((eu . voce) (voce . eu))
          words))
